# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :unit_tests do
    scan(
      scheme: "Actionist",
      code_coverage: true,
      xcargs: "-skipMacroValidation",
      result_bundle: true,  # Generates .xcresult file
      output_types: "",      # Disables additional test output formats
      output_directory: "fastlane/test_results" # Store xcresult elsewhere (optional)
    )
  end
end
