name: iOS CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  run_unit_test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Bundler dependencies
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: macOS-ruby-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            macOS-ruby-
          fail-on-cache-miss: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4

      - name: Install Bundler dependencies
        run: |
          bundle install --path vendor/bundle
        working-directory: ./

      - name: Check installed gems
        run: |
          bundle exec gem list | grep fastlane
        working-directory: ./

      - name: Run Tests
        run: bundle exec fastlane unit_tests
        working-directory: ./
